[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
callee = "8hKjTVHaCE4U2zMYVx5eu5P9MTCU2imhvZZU31jDnYNA"
caller = "8dHQbAAjuxANBSjsEdFMF4d5wMfTS3Ro2DTLaawBLvJ3"
caller_wrapper = "BoU7xvB9ZUrSxpRsYaeKbjj5Xv7MdR2YiSRgMgwoij6k"
hydra_generic = "CJAFX8XgZnTNPbVRUFBYda2b43KzzL7cyVVWFJD9rBby"
lut_manager = "tY637opSt6wHYGQHMkj322aWLT8xxfWkNMidEBeRPqj"
universal_mint = "HfmoA2Urje3qNQ2f9jRuMHepz1aqhG4h6HLeiyntRCe6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/noahgundotra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
